version: '3'
services:
  api:
    container_name: api-server
    environment:
      - 'TZ=Asia/Seoul'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        app: ./build/libs/*.jar

    ports:
    - "80:8080"