spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      maximumPoolSize: 10
      username: sa
      jdbc-url: jdbc:h2:mem:test
#      jdbc-url: jdbc:h2:tcp://localhost/~/test2
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

  jwt:
    secret: qwerqwerqwerqwerqwerqwerqweqwrqweqwrqwr

  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 47788
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
#        type:
#          trace
